### ISSUE TITLE
NativeScript 8 Angular 15 TextField Model Binding missing last char

### ISSUE THREAD

**Issue by arcovoltaico** [NativeScript/angular#119]
I have created an NS Angular Hello World project by running ns create demo. I have just added this to the item-details html:

```
  <TextField [(ngModel)]="demo"></TextField>
  <Label [text]="demo"></Label>
```
and then created the demo property in the component.

Afterwards, I added the NativeScriptFormsModule into the imports of the app.module. So I can see the input and while typing the label is always one char behind, in other words, it's displaying a copy -1 of what it's displayed on the input.

I have the suspicion that for some reason the change is emitted twice. As I can see if I add:

` (textChange)="($event)"`
it emits first an event with the up-to-date value, and just after, another one, that prevails, with the previous value (minus one).

The package.json is at it comes :
{
  "name": "demo",
  "main": "./src/main.ts",
  "version": "1.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "~15.2.0",
    "@angular/common": "~15.2.0",
    "@angular/compiler": "~15.2.0",
    "@angular/core": "~15.2.0",
    "@angular/forms": "~15.2.0",
    "@angular/platform-browser": "~15.2.0",
    "@angular/platform-browser-dynamic": "~15.2.0",
    "@angular/router": "~15.2.0",
    "@nativescript/angular": "^15.0.0",
    "@nativescript/core": "~8.5.0",
    "@nativescript/theme": "~3.0.2",
    "rxjs": "~7.6.0",
    "zone.js": "~0.13.0"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.2.0",
    "@angular/compiler-cli": "~15.2.0",
    "@nativescript/ios": "8.5.2",
    "@nativescript/types": "~8.5.0",
    "@nativescript/webpack": "~5.0.14",
    "@ngtools/webpack": "~15.2.0",
    "typescript": "~4.8.4"
  }
}

**Comment by edusperoni** [comment]
@arcovoltaico This issue only happens on x86 builds on the iOS simulator on iOS 16.4+ (xcode 14.3+). It's not related to NativeScript itself (or angular).

Unfortunately this is something only apple can properly fix:
https://developer.apple.com/forums/thread/727715
https://github.com/NativeScript/NativeScript/issues/10267#issuecomment-1593015385

It won't happen on a real device or arm (M1) simulator builds.

**Comment by arcovoltaico** [comment]
Thanks so much, I am then committing it and hopefully it will work. Thanks!
