### ISSUE TITLE
Nested navigation doesn't work with LazyLoad (iOS)

### ISSUE THREAD

**Issue by Bezlepkin** [NativeScript/angular#121]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 15.2.0
 - Cross-platform modules:
 - Android Runtime: 
 - iOS Runtime: 8.5.2
 - Plugin(s):
 - NativeScript-Angular: 16.0.0
 - Angular: 15.2.0
 
**Describe the bug**
I am trying to make tabs (main navigation) with nested <router-outlet>.

But I want to go to the screen that is outside the <router-outlet>. The transition works. When going back, an error appears (screenshot).

When switching back, the application gives error:
`ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of null (reading 'view')`

![2023-10-01_14-31-50](https://github.com/NativeScript/angular/assets/10475699/6934e5eb-6029-46bc-a44f-f69007d3d478)

**To Reproduce**

**Expected behavior**

**Sample project**
https://github.com/Bezlepkin/ns-ng-tabs-start-app-template

**Additional context**
I also attach a link to video
https://disk.yandex.ru/i/DQ4EGvuLOaJ4xg

**Comment by edusperoni** [comment]
Hello! You're using router-outlet for your tabs outlets. It should be page-router-outlet instead.

**Comment by Bezlepkin** [comment]
@edusperoni Awesome! Is't work! You are best!  Took 24 hours to solve the problem....
