### ISSUE TITLE
Angular 12 migration leads to huge amounts of Change Detection cycles

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/angular#21]
Environment
Provide version numbers for the following components (information can be retrieved by running tns info in your project folder or by inspecting the package.json of the project):

CLI: 8.0.2
"@nativescript/core": "~8.0.0"
"@nativescript/android": "8.0.0",
"@nativescript/ios": "JSC",
"@angular/*": "~12.1.2",
"@nativescript/angular": "~12.0.6"
Describe the bug
After migration to the Angular 12 I am observing huge amounts of Change Detection cycles. About 50 cycles when navigating to an empty page, and about 300 cycles when navigating to a page with content.

Cycles where measured via calls to ngAfterViewChecked().

Note: For everyone observing the same issue. A workaround exists my setting up Angular as follows. I am not sure yet. if this breaks other things:

appModuleBootstrap: (reason: string) =>
platformNativeScript().bootstrapModule(AppModule, { ngZoneEventCoalescing: true })

**Comment by edusperoni** [comment]
This is an unfortunate result of actually patching all the nativescript apis with Zone (It just means a lot of events are firing and we're correctly running CD when that happens).

We should be releasing a beta shortly with https://github.com/NativeScript/angular/pull/26 which also adds support for multithreaded js (js is still single threaded, but the js code may be running in a different android thread). This implementation also uses ngZoneEventCoalescing and ngZoneRunCoalescing set to true by default, so please try it out.

It shouldn't break the app like before. Angular's implementation uses requestAnimationFrame, which may delay things for a full frame, and it's probably what broke a few apps.

To use it, just do:

```
import { NativeScriptNgZone, platformNativeScript, runNativeScriptAngularApp } from '@nativescript/angular';

import { AppModule } from './app/app.module';

runNativeScriptAngularApp({
  appModuleBootstrap: () => platformNativeScript().bootstrapModule(AppModule, {ngZone: new NativeScriptNgZone()}),
});
```

**Comment by cjohn001** [comment]
@edusperoni: Thank you very much for the update. I am currently already playing around with ZoneRun- and EventCoalescing options. Unfortunately, it is breaking different things. I have not reported it yet as I have not had the time to write  demos. Currently I am using it the following way:

platformNativeScript().bootstrapModule(AppModule, { ngZoneRunCoalescing: false, ngZoneEventCoalescing: false }),

When I set ngZoneRunCoalescing = true , transparencies are not rendered correctly. First image shows how it looks like with ngZoneRunCoalescing = false and second one the broken rendering set to true (in both cases ngZoneEventCoalescing: false)

<img width="377" alt="Bildschirmfoto 2021-08-13 um 23 03 55" src="https://user-images.githubusercontent.com/43253483/129418519-49f8a9f3-680a-42ff-8454-ba534b882609.png">

<img width="374" alt="Bildschirmfoto 2021-08-13 um 23 07 54" src="https://user-images.githubusercontent.com/43253483/129418612-de5578b6-706c-4ae1-af86-eaae6246ee7b.png">


When setting ngZoneEventCoalescing: true ( ngZoneRunCoalescing: false) I have found a weird bug together with the use of @nativescript-community/ui-material-tabs. I have a child tab in there which registers to navigatedTo events. In case of the flag set to true the event is not firing.

this.page.on('navigatedTo', this.onNavigatedTo.bind(this));

But as I see from your code snipped I seem to have activated it in the wrong way as I have not provided a new ngZone parameter like you mentioned. I will try this and report back to you as soon as possible. I broke another plugin, which I first need to fix before looking at it :)

**Comment by edusperoni** [comment]
@cjohn001 the beta version is still not up, it seems, @NathanWalker should publish it later.

I saw cases of the app breaking like that, and with this new NgZone it seems that's fixed. About the `navigatedTo` event and others, please note that `ngOnInit` may be called AFTER `navigatedTo` because `ngOnInit` runs at the first CD cycle. If you need to catch these events, it's better to bind them on constructor, just beware that your callbacks may be called before `ngOnInit`

**Comment by cjohn001** [comment]
> @cjohn001 the beta version is still not up, it seems, @NathanWalker should publish it later.
> 
> I saw cases of the app breaking like that, and with this new NgZone it seems that's fixed. About the `navigatedTo` event and others, please note that `ngOnInit` may be called AFTER `navigatedTo` because `ngOnInit` runs at the first CD cycle. If you need to catch these events, it's better to bind them on constructor, just beware that your callbacks may be called before `ngOnInit`

Thanks for the advice. Unfortunately, the registration of the event I am doing already in the constructor

**Comment by edusperoni** [comment]
Btw, I added a helper for these kinds of events (still undocumented and subject to change in the future):

```
@NativeScriptNgSafeEvent('ngOnInit')
myCallback() {
  console.log('this will never run before ngOnInit')
}
```

that's useful for nativescript callbacks as they can be called before the components are ready, so you can delay them.

If you're having issues and it's being registered in the constructor, most likely the page is already loaded and your view was created after initial CD (like when it's wrapped in an ngIf). You can use `PageService` that has a lot of goodies around this, and also keeps track if the page is the current one or not:

```
constructor(pageService: PageService) {
  this.pageService.inPage$.subscribe((isInPage) => /* isInPage is true when the page is the current one */);
}
```
you can also use `pageEvents$` which will fire all the 4 page navigation events

**Comment by cjohn001** [comment]
Ok, great, thanks a lot! So you recommend to not stick with navigatedTo event but use one of these mechanisms? Or you consider it as a workaround till we get the navigatedTo stuff right? In that case I would provide a bug report

**Comment by edusperoni** [comment]
@cjohn001 I consider the best practice to not rely on `navigatedTo` for components that are not pages themselves (aren't used in the routing module). The reason being that, for example, if you have them in a tabview, listview, or others that are similar, the templates may not be loaded at the start (tabview keeps a few tabs unloaded, so depending on how your view was rendered, you can't guarantee that the component will be shown synchronously, so it'll miss the first navigation event).

I believe current lifecycle is:
```
navigatingTo
// render the page component here
page.isLoaded = true;
navigatedTo
// CD might have kicked in async and create pending templates here
navigatingFrom
page.isLoaded = false;
navigatedFrom
```

The most reliable way to check if you're in page is to check if the page is loaded (or use PageService, which will do that for you). This happens a lot with the `loaded` event, the only reason you don't see issues about it is because we do some special handling (we manually fire a 'loaded' event when you're trying to bind 'loaded' to an already loaded view):

https://github.com/NativeScript/angular/blob/main/packages/angular/src/lib/nativescript-renderer.ts#L261-L269

**Comment by edusperoni** [comment]
@cjohn001 a new rc was just published, you can try it now.

**Comment by cjohn001** [comment]
Thank you very much for the info. Then I will go with the PageService in the future. I assume it is part of nativescript/angular as well? 
Maybe a last question which is a little of topic, but I have not so often the chance to speak with someone so deep involved :) The only reason I am currently working with page events in Angular is, that I have issues with page transitions (very bad on Android). I typically use a data service to bring the data in to the component. I set the observables of the service usually up in ngOnInit. Unfortunately, I often run into the situation, that they fire during the page. The transition then breaks (no smooth transition) In this situtation I store the data from the dataservice in a temporary variable and then bind them to the component on pageLoaded. I unfortunately have not a found a description yet if for nativescript, ngOnInit is the right way to set up observables. And a second issue of it is, that I always have to show a loading message as the page has to be rendered twice. I have seen that I can preload data with a kind of route guard. Maybe this is the better way to go. Have not tried this yet as I assumed page transitions then feel even slower. What would be your recommendation to bring in the data from the service without interfering the page transitions?

**Comment by cjohn001** [comment]
> @cjohn001 a new rc was just published, you can try it now.

I am on it

**Comment by cjohn001** [comment]
@edusperoni , @NathanWalker:  Very great work gentlemen. My app now for the very first time feels like a real native app. Huge performance gain!! I have one issue with it left now. Nathan know the issue already. I have a problem with the pro-ui calendar (not an angular thing) which at initial rendering always renders with the default styles rather than the configured styles. 
I have access to the plugins-ui repo. After the latest changes in the repo I am unfortunately not able anymore, to build the native calendar demo. A webpack dependency is reported missing which I cannot resolve, I posted an issue in the plugins-ui repo with the error log. If someone of you could look into this, I would invest the rest of the weekend to try to solve the calendar bug thing, see video attached. With the great performance gain the initially loaded calendar view now always appears broken. Before, one could only observe the problem when the app came from background.


https://user-images.githubusercontent.com/43253483/129424818-3ab56cf1-8313-4baf-8912-701d7f4b8e59.mov

**Comment by NathanWalker** [comment]
Thanks @cjohn001 I’ll take a look at that repo in a bit.

**Comment by NathanWalker** [comment]
@cjohn001 https://github.com/NativeScript/plugins-ui/issues/6#issuecomment-898772644

**Comment by cjohn001** [comment]
@edusperoni, @NathanWalker : Hello, I would like to come back on you regarding the new ns zone feature:

ngZone: new NativeScriptNgZone({
				enableLongStackTrace: false,
				shouldCoalesceEventChangeDetection: true,
				shouldCoalesceRunChangeDetection: true
			})

On some pages of my app, I am now observing wrongly computed layouts during initial rendering. If I set both coalescing features to false the layouts are working. Attached you see two pictures of a page transition sequence. One can see that the header height looks broken during the transition. The header is in a grid layout with row set to auto in the normal case. However, I did extensive testing now. Even if I set the row-height to a fixed height, say row="150" the. height is wrong during initial rendering. Would be great if you could have another look into the optimization.

**Comment by edusperoni** [comment]
@cjohn001 can you try it with this? https://drive.google.com/file/d/1_akzc_l_Tb5NxcUqF8gGFgr7MOOs4lXz/view?usp=sharing

It's the packed https://github.com/NativeScript/angular/pull/27. Should trigger CD before the views are attached to the native view tree at all

**Comment by cjohn001** [comment]
@edusperoni : Thank you very much for your help!. The hint is very valuable. Great news, your last fix, to explicitly trigger CD is the solution. Everything is looking normal now!

Now where this is working, I have one other question regarding what I am seeing with the ui pro calendar. After looking into the code for the whole weekend, where things seem to look ok, I am now wondering, if my problem also has to do with the renderer and not with the plugin itself. 
It seem like when the app resumes from background, the code path is somewhat different from the normal rendering path. For example, the loaded event of the calendar is triggered after the screen was already rendered for the first time. During normal page transitions loaded event fires before page shows up. Please have a look at the attached video. The problem is, when the app was in background and is started again, then for the first rendering the default styles are applied (hard coded in objective c code and not the styles applied with the property bindings). 
Similar like the issue you have just solved with the CD, the Property binding value changed events are not triggered before rendering. I tried the calendar resume again with your new fix. Unfortunately, the problem still exists for the calendar. Might there be a CD update missing in a different code path when the app resumes from background as well? Hence, another issue in the renderer and not in the pro-ui plugin?


https://user-images.githubusercontent.com/43253483/129530694-96116a9d-b4a7-4385-9d31-ef1ab1fe164f.mov

**Comment by edusperoni** [comment]
@cjohn001 didn't this issue happen prior to this? On resume, if the binding values haven't changed, I don't think angular will apply anything. As for the loaded event, that's something that happens on core. If you need CD to run on the loaded event, you can call it yourself (this.cdref.detectChanges())

**Comment by cjohn001** [comment]
@edusperoni : You are right, the issue exists already since at least. 1.5 years. So if I understand you correctly,  suspending and resuming that app should not lead to a view being rebuild. Seems like for the calendar this is the case. As one can see from the image, when the app comes up the calendar has the default styles applied. I thought on suspend of the app the views get destroyed. Maybe this helps me to isolate the issue.

Running change detection from loaded event to force an update on the calendar after resume is unfortunately too late. The calendar already shows up on screen before the loaded event fires.

**Comment by edusperoni** [comment]
No views are destroyed on suspend. It seems like a calendar bug as it's probably changing styles/delegates on unloaded and setting them again on loaded.

Angular's CD won't "re-apply" any properties that haven't changed. if you do:

`<Label backgroundColor="black">`, angular will set the background color on the first CD. If you change it with loaded or whatever (label.backgroundColor=blue), the color will remain blue no matter how many CD cycles you go through. It keeps track of every property it sets and during CD it reevaluates the values and compare with the previous one, if they differ, it'll call setProperty.

**Comment by cjohn001** [comment]
@edusperoni : Thanks for the info. Then I will have a second look to the calendar. Must be the calendar events than.

One final question regarding the Angular plugin performance. I am now trying to get things running on Android. My problem is here, that the page transition animations are stuttering, when there are UICollectionViews (lists) on the page to be opened. It seems that rendering is interfering with the data being rendered on the collection view. I first suspected that the transition animation might not be on the same ui tread like the javascript things running, and that my observables pulling in the view data might interfere with the transition animation. I thought I can resolve the topic by preloading data from a route resolver. However, this also does not work.  Do you have an idea how I could resolve the issue to get smooth page transitions? 
I do not want to transition to the page, show a loading animation, and then display the collection view. UI looks a lot better if I can directly show the filled list.

**Comment by edusperoni** [comment]
Views are created when you update your listview, if that happens when you're navigating, it'll slow things down. The heavier the views, the more processing (and frames) it'll take to create. You can try a RouteResolver, so the view will have the data on creation, which may make things better, but introduce a delay after the user requests a navigation (tap to navigate), or you can delay dispatching these items to your listview with the `combineLatest` operator I listed above.

Unfortunately, that is pretty much how things go on most mobile apps, you either have your views ready on navigate or there's usually a backend (or artificial) delay to load them. If you have a gauge and multiple complex views, it's going to introduce slowdowns.

**Comment by cjohn001** [comment]
@edusperoni. I am not sure than what I am doing wrong. I thought with my approach I should have the views ready when I navigate. I resolve data with a route resolver already and than in ngOnInit get them from the route

this._searchEntries = this.activatedRoute.snapshot.data['cachedProducts'];

Hence, I would expect that the renderer awaits the views to be ready before it transitions to the page. Do you mean I need to manually give the view more time to be prepared? How would I include such a delay? I mean, I can just call

this.router.navigate([this._defaultNavTarget], {
					transition: { name: 'slideLeft' },
					clearHistory: false
				});

Or can I provide the router some parameter to wait a delay after I requested the transition. I am not sure how I should do it. On the route resolver, I also do not know how I should include an additional delay. The resolver waits till the observable completes, hence also not an option to include a delay.

**Comment by cjohn001** [comment]
@edusperoni, I close the issue here now. I in the meantime suspect that the problems I see with rendering on page transitions is related to the ui collectionview plugin I am using. The problem only appears will pages on which this collection view is used. In case it is a general problem I would open another issue here.
