### ISSUE TITLE
zone-js package still as copy in repo

### ISSUE THREAD

**Issue by saschaarthur** [NativeScript/angular#23]
Hello,

Loving how the team got rid of the custom zone-js. Good Job!

Was following with https://github.com/NativeScript/nativescript-angular/issues/2278#issuecomment-861852490 to implement the rejection handler via Zone-JS API which works like a charm.

So fine so good. 

But what im still wondering is.. Why is the zone-js still as a copy in repo here: https://github.com/NativeScript/angular/tree/main/packages/zone-js/dist

Shouldnt it be enough (and much cleaner) to reference the needed package just via package.json? 

Im feering someone will in future start patching the zone-js again. 

Also it would be awesome to get the source code attached to this NPM repo https://www.npmjs.com/package/@nativescript/zone-js (even though its only for angular 11?)

**Comment by edusperoni** [comment]
We will no longer use a custom zone.js implementation. The @nativescript/zone-js package now contains zone patches related to Nativescript that need to be included in polyfills.ts (just like zone.js is included in the polyfills).

Zone patches are required for many platforms, and you'd usually include them in your polyfills directly from zone.js/dist/platform, we're just opting to provide our own package with the freedom it entails.
