### ISSUE TITLE
regression: nsTemplateKey not being able to be used by other plugins

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/angular#24]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 8.0.0
 - Cross-platform modules: 8.0.8
 - Android Runtime: 8.0.0
 - iOS Runtime: 8.0.0
 - Plugin(s):
 - NativeScript-Angular: 12.0
 - Angular: 12.1
 
**Describe the bug**
Seems with the rewrite to NG 12 the standardized classes for Templated Items Components were removed. This basically prevents plugins from using the `nsTemplateKey` directive to specify their own item templates. Plugins now need to define unique directive keys for each plugin, this basically makes it difficult for developers to remember what key they should use with what component/plugin. 

Any idea why the code was removed @NathanWalker & @edusperoni ? Here is the PR with which I have added the standardization in the old NS angular plugin and this was working fine pre-12:
https://github.com/NativeScript/nativescript-angular/pull/1520

If there are problems with the old standardization way and how it was used, can we think of some other way so that other plugins can re-use the `nsTemplateKey` directive and not create their own ones?

**To Reproduce**

**Expected behavior**

**Sample project**

**Additional context**

**Comment by edusperoni** [comment]
Implemented in #32
