### ISSUE TITLE
Please add support for Angular 14

### ISSUE THREAD

**Issue by cjohn001** [NativeScript/angular#70]
Hello together,
would be great if you could add support for Angular 14. 

**Environment**
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.2.3 version and is up to date.
✔ Component @nativescript/core has 8.2.4 version and is up to date.
✔ Component @nativescript/ios has 8.2.3 version and is up to date.
✔ Component @nativescript/android has 8.2.3 version and is up to date.
 - NativeScript-Angular: "@nativescript/angular": "13.0.4",
 - Angular: 14.0.0

**Describe the bug**
When building my app against Angular 14 the app crashes on startup. Seems like I am currently running into breaking changes with Angular 14.

CONSOLE LOG: Angular is running in development mode. Call enableProdMode() to enable production mode.
CONSOLE ERROR: ERROR Error: Uncaught (in promise): TypeError: loadedResolver.resolveComponentFactory is not a function
TypeError: loadedResolver.resolveComponentFactory is not a function
at PageRouterOutlet.getComponentFactory (file:///app/vendor.js:291130:46)
at PageRouterOutlet.activateOnGoForward (file:///app/vendor.js:290954:26)
at PageRouterOutlet.activateWith (file:///app/vendor.js:290944:12)
at ActivateRoutes.activateRoutes (file:///app/vendor.js:266319:31)
at file:///app/vendor.js:266259:17
at Array.forEach (<anonymous>)
at ActivateRoutes.activateChildRoutes (file:///app/vendor.js:266258:27)
at ActivateRoutes.activateRoutes (file:///app/vendor.js:266326:16)
at file:///app/vendor.js:266259:17
at Array.forEach (<anonymous>)

**Comment by rob4226** [comment]
Looking forward to Angular 14 on NS also. Thank you! 🙏

**Comment by NathanWalker** [comment]
@cjohn001 @rob4226 `rc` is up now:

```
@nativescript/angular 14.0.0-rc.0
```

Please let us know if you encounter anything.

**Comment by NathanWalker** [comment]
https://github.com/NativeScript/angular/releases/tag/14.0.0
