### ISSUE TITLE
iOS - Angular animations now cause app to crash

### ISSUE THREAD

**Issue by JWiseCoder** [NativeScript/angular#90]
Upgrading to Angular 14 now causes animations (that used to work) to crash this app with error:

`NativeScript encountered a fatal error: Uncaught Error: No known animation properties specified`

I think I tracked this down to where it's happening.  In `packages/angular/src/lib/animations/utils.ts`, the `getDeclarations` function receives the `styles` param as type KeyFrame, which is defined at the top of that file as a Map type.  However, in the body of the `getDeclarations` function, it's calling `Object.keys` on the `styles` Map, which won't give the desired results.  I modded this file in my app's node_modules to get the keys from the Map correctly, and the animations work without crashing.

I think this may have just been an oversight when updating for use with Angular 14 in commit af32ad7dd8a0eedb1702917e8207fcb55230b900.

**Comment by NathanWalker** [comment]
That makes ton of sense! Would you want to try posting a PR? We can patch in next couple days.

**Comment by NathanWalker** [comment]
Fixed in 14.2.4 thank you @JWiseCoder

**Comment by JWiseCoder** [comment]
Great!  Thanks!
